### PR TITLE
Fix a few unrelated frontend issues

### LINKED ISSUE #1053: Accordion tracks sometimes truncated with scrollbars
I tried to clear out cache, thinking there's some old html in there, but it seems to persist. Something to do with the last deploy / seekbars?...

Screenshot 2020-10-20 - Alter Ego's Music | alonetone 2

### LINKED ISSUE #1058: View Track Detail Page… line wraps awkwardly on 768px screen double column

### LINKED ISSUE #1059: on user home, sort & edit playlists >, the caret wraps poorly on iOS but not desktop

### LINKED ISSUE #1061: Check Big Player play button click zone, on iPad click a quick flash there is unflattering

### PR DESCRIPTION
**Pull request by ofsound**
Fixes #1061 

Clicking play on iPad reveals this anchor shape.

Screen Shot 2020-11-30 at 7 09 14 PM

On the branch, this section is rewritten so the anchor can be styled as a block, and inherit the shape of its contents:

Screen Shot 2020-11-30 at 7 11 04 PM

Fixes #1059 

On iOS, maybe due to some specific font nuance, this caret was jumping down to the next line. I rewrote the double space before the caret more explicitly with &nbsp; to fix it.

IMG_9358

Fixes #1058 

This was brought up by childhoodsend, but also very noticeable using AT on portrait iPad, 768px wide, as well as an iPhone with a 320px wide view.

Screen Shot 2020-11-30 at 7 17 06 PM

The current solution on the branch was to add an alternate text for those 2 width ranges, Narrow 2 column view, and small mobile phone. But maybe there's a better fix?

Screen Shot 2020-11-30 at 7 22 30 PM

This brings up perhaps that the Percy mobile view should be smaller, as this text change made it through Percy?

Fixes #1053

This is illustrated in the Issues, with alter ego as the example. The branch code moves where that css margin style is, so a track view without comments doesn't collapse:

Screen Shot 2020-11-30 at 7 25 36 PM

The other change is to slightly update the Toggle drag sliders on Edit playlist, so they aren't transparent and very broken on dark theme. Also, the original design from Figma seemed to have been lost somewhere along the way, with an extra element. Some other UI elements, X and +I don't think have dark theme designs in Sigma, so right now, I kept the toggles universal, same for white and dark.

Current:

Screen Shot 2020-11-30 at 7 31 05 PM

Branch:

Screen Shot 2020-11-30 at 7 31 28 PM

### Does anything special need to happen for deployment?

No. 

## "Ready For Review" checklist

These checklists are to help ensure the code review basics are covered. Consider removing to reduce noise.

* [ ] PR title accurately summarizes changes
* [ ] New tests were added for isolated methods or new endpoints
* [ ] I opened an issue for any logical followups
* [ ] If this fixes a bug, "Fixes #XXX" is either the very first or very last line of the description.

## Before code review *and after additional commits* during review.

* [ ] Update title and description to account for additional changes
* [ ] All tests green
* [ ] Migrations were tested locally and do the right thing
* [ ] Booted up the branch locally, exercised any new code
* [ ] Percy changes are purposeful or explained
* [ ] Css changes are happy on mobile (via Percy is ok)

### CODE REVIEW

File: db/schema.rb [hunk 1]
```diff
@@ -25,16 +25,6 @@
...
-  create_table "action_text_rich_texts", charset: "utf8mb4", collation: "utf8mb4_unicode_ci", force: :cascade do |t|
-    t.string "name", null: false
-    t.text "body", size: :long
-    t.string "record_type", null: false
-    t.bigint "record_id", null: false
-    t.datetime "created_at", precision: 6, null: false
-    t.datetime "updated_at", precision: 6, null: false
-    t.index ["record_type", "record_id", "name"], name: "index_action_text_rich_texts_uniqueness", unique: true
-  end
-
```
Comment (sudara) [inline db/schema.rb:37]: I shouldn't have committed this to master, glad it got caught here.

File: db/schema.rb [hunk 2]
```diff
@@ -57,7 +47,7 @@
     t.index ["key"], name: "index_active_storage_blobs_on_key", unique: true
   end
 
-  create_table "active_storage_variant_records", charset: "utf8mb4", collation: "utf8mb4_unicode_ci", force: :cascade do |t|
+  create_table "active_storage_variant_records", charset: "utf8mb4", force: :cascade do |t|
```
Comment (sudara) [inline db/schema.rb:50]: Locally I have collation set in my datbase.yml to `utf8mb4_unicode_ci` in efforts to resolve https://github.com/sudara/alonetone/issues/732 — so this change is desirable.

**Comment by sudara** [comment]
Thanks for the visual description of changes — quite useful!!
