### PR TITLE
Fix or improve several miscellaneous responsive/mobile issues

### LINKED ISSUE #1060: Edit Profile social media link / change login inputs are uncomfortably small on mobile

### PR DESCRIPTION
**Pull request by ofsound**
Fixes #1060

**fix bad update login button on edit profile**

> Screen Shot 2021-01-19 at 1 35 19 PM
> 
> to
> 
> Screen Shot 2021-01-19 at 1 35 36 PM

**add line break on change your login ( check this again on thin mobile )**

> Screen Shot 2021-01-19 at 1 35 57 PM
> 
> to
> 
> Screen Shot 2021-01-19 at 1 36 28 PM

**danger flags on responsive screens can seem strangely positioned**

> Screen Shot 2021-01-19 at 1 37 16 PM
> 
> to 
> 
> Screen Shot 2021-01-19 at 1 37 28 PM
> 

**freshabeats breaks "Latest Listens To Your Music", artist name within accordions,** 

> Screen Shot 2021-01-19 at 1 38 05 PM
> 
> to
> 
> Screen Shot 2021-01-19 at 1 38 23 PM

**better dividing lines on Edit Profile > Settings**

> Screen Shot 2021-01-19 at 1 38 39 PM
> 
> to
> 
> Screen Shot 2021-01-19 at 1 38 59 PM

**artist name, follow and the avatar responsive breakdown**

> Screen Shot 2021-01-19 at 1 39 24 PM
> 
> to 
> 
> Screen Shot 2021-01-19 at 1 39 39 PM
> 

**social links display are a mess on user page ( refactor CSS to be more readable? switch to JS class swap? )**

> Screen Shot 2021-01-19 at 1 40 26 PM
> 
> to 
> 
> Screen Shot 2021-01-19 at 1 40 34 PM

**social links in edit profile to two line style ( better design, what do other sites do? )**

> Screen Shot 2021-01-19 at 1 41 04 PM
> 
> to 
> 
> Screen Shot 2021-01-19 at 1 41 20 PM

**followers grid (remove test loop that creates many avatars)**

> Screen Shot 2021-01-19 at 1 41 48 PM
> 
> to 
> 
> Screen Shot 2021-01-19 at 1 41 33 PM
> 

## "Ready For Review" checklist

These checklists are to help ensure the code review basics are covered. Consider removing to reduce noise.

* [x] PR title accurately summarizes changes
* [x] New tests were added for isolated methods or new endpoints
* [ ] I opened an issue for any logical followups
* [x] If this fixes a bug, "Fixes #XXX" is either the very first or very last line of the description.

## Before code review *and after additional commits* during review.

* [ ] Update title and description to account for additional changes
* [ ] All tests green
* [ ] Migrations were tested locally and do the right thing
* [x] Booted up the branch locally, exercised any new code
* [x] Percy changes are purposeful or explained
* [x] Css changes are happy on mobile (via Percy is ok)

### CODE REVIEW

**Review by sudara — APPROVED** [review]
Looking really good! Excited to merge once the while loop is removed :)

File: app/javascript/controllers/followees_controller.js [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+
+export default class extends Controller {
+  
+  connect() {
+    this.resize()
+  }
+
+  resize() {
+
+    let containerWidth = this.element.clientWidth - 24
```
[the remark this answers is not in the document]
Comment (sudara) [reply app/javascript/controllers/followees_controller.js:11]: If you aren't seeing these locally, it might be worth spending a few min together figuring out why eslint isn't triggering in vscode.

File: app/assets/stylesheets/components/user.scss [hunk 2]
```diff
@@ -442,21 +441,166 @@ main {
...
+              a {
+                border-right: 2px solid #000;
+              }
+            }
+            &:nth-child(3n + 1) {
+              border-radius: 0;
+              a {
+                border-right: 2px solid #000;
+              }
+            }
```
Comment (sudara) [inline app/assets/stylesheets/components/user.scss:587]: Is there a reason these are expanded or can we collapse them to 

&:nth-child(6n), 
&:nth-child(6n + 1),
etc

**Comment by sudara** [comment]
Is the padding change on track chunk artist names that percy is showing intentional / desired?

File: app/javascript/controllers/followees_controller.js [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+    const containerWidth = this.element.clientWidth - this.containerPadding
+    const avatarsPerRow = Math.round(containerWidth / this.avatarWidthFromCSSPlusMargin)
+    const totalMarginWidth = this.avatarMargin * (avatarsPerRow)
+    const totalAvailableWidth = containerWidth - totalMarginWidth
+    const calculatedAvatarWidth = totalAvailableWidth / avatarsPerRow
+
+    if (this.totalFollowees >= avatarsPerRow) {
+      const childrenArray = [...this.element.children]
+      childrenArray.forEach((avatar) => {
+        const thisAvatar = avatar
```
Comment (sudara) [inline app/javascript/controllers/followees_controller.js:27]: this line should maybe be removed, and `avatar` used below
